Added Recommendation Cards API endpoint
yoshiask/FluentStore pull request #2
Opened 2020-09-21 20:18 UTC by ahmed605

2020-09-21 21:02 UTC, yoshiask requested changes

2020-09-22 02:26 UTC, ahmed605 commented on MicrosoftStore/Models/Recommendations.cs
> +    public class Recommendations
Fixed!

2020-09-22 02:27 UTC, ahmed605 commented on MicrosoftStore/Enums/ImageType.cs
> +        BoxArt,
I was adding the attributes to the model properties directly but I moved them to the enum now

2020-09-22 02:28 UTC, ahmed605 commented on MicrosoftStore/IStorefrontApi.cs
> +        Task<Recommendations> GetHomeRecommendations(string market = "US", string locale = "en-US", string appversion = "11905.1001.0.0", int pageSize = 15);
Nope, just making it easy to use the endpoint without using many arguments

2020-09-22 03:41 UTC, yoshiask requested changes

2020-09-22 03:41 UTC, yoshiask commented on MicrosoftStore/Enums/ImageType.cs
> +        BoxArt,
I mean on the enum values. It doesn't need to have specified strings for each enum value, or are they all deserialized properly?

2020-09-22 04:20 UTC, ahmed605 commented on MicrosoftStore/Enums/ImageType.cs
> +        BoxArt,
it needs this in case if vales names don't match their names in JSON only

2020-09-22 22:54 UTC, yoshiask approved these changes

2020-09-22 22:56 UTC, merged